name: CHEHungerGames
version: 1.0
main: che.mchg.Main

commands:
  setspawnpos:
    description: Sets the location for a specific spawn point
    permission: hg.setspawnpos
    
permissions:
  hg.setspawnpos:
    description: Gives access to /setspawnpos
    default: op